services:
  - type: web
    name: java-item-management
    env: docker
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_OPTS
        value: -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8